<a target="_blank" href="https://colab.research.google.com/github/vnstock-hq/vnstock_insider_guide/blob/main/demo/1-demo_vnstock_data_v2_quickstart.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Thiết lập

## Google Colab

In [ ]:
!git clone https://github.com/vnstock-hq/vnstock_insider_guide
%cd /content/vnstock_insider_guide/oneclick_installer
!chmod +x linux_installer.run

In [ ]:
!./linux_installer.run

# Minh hoạ

## 1. Thống kê giao dịch

In [ ]:
from vnstock_data import Trading
trading = Trading(symbol='FPT')
START_DATE = '2024-01-02'
END_DATE = '2025-03-22'

### Lịch sử giá

In [2]:
trading.price_history(start=START_DATE, end=END_DATE)

2025-03-22 15:52:37 - vnstock_data.explorer.cafef.trading - INFO - Lịch sử giá:
Mã CK: FPT. Số bản ghi hợp lệ: 300

,open,high,low,close,adjusted_price,change_pct,matched_volume,matched_value,deal_volume,deal_value
time,,,,,,,,,,
2025-03-21,125.0,129.0,125.0,128.0,128.00,0.0240,6424800,820204000000,0,0
2025-03-20,124.6,126.8,124.5,125.0,125.00,0.0032,8203400,1027201000000,505200,63256092000
2025-03-19,130.1,130.6,123.5,124.6,124.60,-0.0415,18128400,2288715000000,1136000,146910000000
2025-03-18,130.1,132.2,130.0,130.0,130.00,0.0000,5508500,719729000000,120000,15534800000
2025-03-17,131.6,132.1,129.6,130.0,130.00,-0.0107,6707000,874898000000,916000,119080000000
...,...,...,...,...,...,...,...,...,...,...
2024-01-08,97.4,98.3,97.1,97.3,83.45,-0.0010,1443000,140899000000,110400,11503680000
2024-01-05,97.3,97.5,96.5,97.4,83.53,0.0021,1138600,110465000000,362700,36610780000
2024-01-04,96.3,98.4,96.2,97.2,83.36,0.0093,2973900,289657000000,26700,2571210000
2024-01-03,95.6,96.5,95.4,96.3,82.59,0.0042,1436900,137664000000,122000,11699800000
2024-01-02,96.9,96.9,95.7,95.9,82.25,-0.0021,1714500,164846000000,503277,51736862200

### Thống kê đặt lệnh

In [3]:
trading.order_stats(start=START_DATE, end=END_DATE)

2025-03-22 15:52:37 - vnstock_data.explorer.cafef.trading - INFO - Thống kê đặt lệnh:
Mã CK: FPT. Số bản ghi hợp lệ: 298

,buy_orders,sell_orders,buy_volume,sell_volume,volume_diff,avg_buy_order_volume,avg_sell_order_volume
time,,,,,,,
2025-03-21,12215,11719,12135400,12266800,"-131,400",993.48,1047
2025-03-20,13899,8742,14561400,11804400,"2,757,000",1047.66,1350
2025-03-19,36314,15221,28048200,26193600,"1,854,600",772.38,1721
2025-03-18,11750,6548,10752100,8310000,"2,442,100",915.07,1269
2025-03-17,15511,7327,11796600,10266200,"1,530,400",760.53,1401
...,...,...,...,...,...,...,...
2024-01-08,1507,2972,2505500,3949800,"-1,444,300",1662.57,1329
2024-01-05,1569,1901,2302100,2769400,"-467,300",1467.24,1457
2024-01-04,2367,4246,4835700,6039300,"-1,203,600",2042.97,1422
2024-01-03,2496,1737,2672800,2388400,"284,400",1070.83,1375
2024-01-02,2034,1530,2814800,3444300,"-629,500",1383.87,2251

### Giao dịch nước ngoài

In [4]:
trading.foreign_trade(start=START_DATE, end=END_DATE)

2025-03-22 15:52:38 - vnstock_data.explorer.cafef.trading - INFO - Lịch sử GD Nước ngoài:
Mã CK: FPT. Số bản ghi hợp lệ: 297

,fr_net_volume,fr_net_value,fr_buy_volume,fr_buy_value,fr_sell_volume,fr_sell_value,fr_remaining_room,fr_ownership
time,,,,,,,,
2025-03-21,0,0,0,0,0,0,0,0.00
2025-03-20,0,0,0,0,0,0,643077920,0.00
2025-03-19,-8496243,-1072042879200,1806878,228946830100,10303121,1300989709300,0,0.00
2025-03-18,-2405303,-314234133200,826788,108045848000,3232091,422279981200,0,0.00
2025-03-17,-2079059,-271094441400,460436,60071848600,2539495,331166290000,0,0.00
...,...,...,...,...,...,...,...,...
2024-01-08,-11500,-1121480000,0,0,11500,1121480000,26924,56.35
2024-01-05,2100,204330000,2100,204330000,0,0,15424,56.35
2024-01-04,400,38520000,400,38520000,0,0,17524,56.35
2024-01-03,0,0,0,0,0,0,17924,56.35
2024-01-02,15800,1532910000,17900,1734510000,2100,201600000,0,49.00

### Thống kê giao dịch tự doanh

In [5]:
trading.prop_trade(start=START_DATE, end=END_DATE)

2025-03-22 15:52:38 - vnstock_data.explorer.cafef.trading - INFO - Lịch sử GD Tự Doanh:
Mã CK: FPT. Số bản ghi hợp lệ: 302

            prop_buy_volume  prop_sell_volume  prop_buy_value  prop_sell_value
time
2025-03-21           333200            228800     42591580000      29176970000
2025-03-20           319900             86500     40077650000      10846730000
2025-03-19          2122200            430700    271717260000      53877040000
2025-03-18           213300            243300     27882370000      31780970000
2025-03-17           247300           1253700     32180280000     163207060000
...                     ...               ...             ...              ...
2024-01-08           202800            229400     19799970000      22366190000
2024-01-05           145600            206800     14135280000      20074670000
2024-01-04           766800            118700     74706660000      11583020000
2024-01-03            39500            464800      3784210000      44480110000
2024-01-02           123000            151900     11869050000      14587780000

[302 rows x 4 columns]

### Thống kê giao dịch nội bộ

In [6]:
trading.insider_deal(start='2024-01-02', end=END_DATE)

2025-03-22 15:52:38 - vnstock_data.explorer.cafef.trading - INFO - Thống kê giao dịch Cổ Đông & Nội bộ:
Mã CK: FPT. Số bản ghi hợp lệ: 13

,symbol,holder_id,transaction_man,transaction_man_position,related_man_position,related_man,volume_before_transaction,plan_buy_volume,plan_sell_volume,plan_begin_date,plan_end_date,real_buy_volume,real_sell_volume,real_end_date,published_date,order_date,volume_after_transaction,transaction_note,shareholder_code,ownership_percentage
0,FPT,0,Bùi Quang Ngọc,Phó Chủ tịch HĐQT,,,23961492,0,2000000,2025-02-05 17:00:00,2025-02-27 17:00:00,0,2000000,2025-02-10 17:00:00,2025-02-03 17:00:00,2025-02-05 17:00:00,21961492,,CEO_00011,1.492893
1,FPT,0,Nguyễn Việt Thắng,Trưởng BKS,,,185841,0,60000,2024-10-16 17:00:00,2024-11-14 17:00:00,0,60000,2024-11-12 17:00:00,2024-10-14 17:00:00,2024-10-16 17:00:00,125841,,CEO_08530,0.008554
2,FPT,0,Đỗ Thị Ngọc Mai,Con,Phó Tổng GĐ,Đỗ Cao Bảo,1046636,75659,0,2024-10-07 17:00:00,2024-10-08 17:00:00,75659,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,1122295,Mua cp ESOP,LQ_80480,0.076291
3,FPT,0,Mai Thị Lan Anh,Công bố thông tin,,,36,3025,0,2024-10-07 17:00:00,2024-10-08 17:00:00,3025,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,3061,,CEO_872090,0.000208
4,FPT,0,Nguyễn Khải Hoàn,Thành viên BKS,,,1234527,182203,0,2024-10-07 17:00:00,2024-10-08 17:00:00,182203,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,1416730,Mua cp ESOP,CEO_06479,0.096306
5,FPT,0,Nguyễn Văn Khoa,Tổng Giám đốc,,,3962387,360414,0,2024-10-07 17:00:00,2024-10-08 17:00:00,360414,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,4322801,Mua cp ESOP,CEO_82590,0.293854
6,FPT,0,Phạm Minh Tuấn,Phó Tổng GĐ,,,556826,1161702,0,2024-10-07 17:00:00,2024-10-08 17:00:00,1161702,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,1718528,Mua cp ESOP,CEO_99721,0.116822
7,FPT,0,Nguyễn Việt Thắng,Trưởng BKS,,,170711,15130,0,2024-10-07 17:00:00,2024-10-08 17:00:00,15130,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,185841,Mua cp ESOP,CEO_08530,0.012633
8,FPT,0,Nguyễn Thế Phương,Phó Tổng GĐ,,,4750998,216313,0,2024-10-07 17:00:00,2024-10-08 17:00:00,216313,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,4967311,Mua cp ESOP,CEO_07229,0.337667
9,FPT,0,Hoàng Hữu Chiến,Kế toán trưởng,,,657657,86422,0,2024-10-07 17:00:00,2024-10-08 17:00:00,86422,0,2024-10-08 17:00:00,2024-10-04 17:00:00,2024-10-07 17:00:00,744079,Mua cp ESOP,CEO_03844,0.050581
10,FPT,0,Nguyễn Khải Hoàn,Thành viên BKS,,,1173502,0,100000,2024-03-06 17:00:00,2024-03-31 17:00:00,0,100000,2024-03-10 17:00:00,2024-03-04 17:00:00,2024-03-06 17:00:00,1073502,,CEO_06479,0.072974
11,FPT,0,Nguyễn Việt Thắng,Trưởng BKS,,,183445,0,35000,2024-01-29 17:00:00,2024-02-27 17:00:00,0,35000,2024-02-01 17:00:00,2024-01-25 17:00:00,2024-01-29 17:00:00,148445,,CEO_08530,0.010091
12,FPT,0,Nguyễn Việt Thắng,Trưởng BKS,,,183445,0,35000,2024-01-08 17:00:00,2024-01-18 17:00:00,0,0,2024-01-18 17:00:00,2024-01-04 17:00:00,2024-01-08 17:00:00,183445,,CEO_08530,0.012470

## 2. Giá lịch sử (đã điều chỉnh) & thống kê giao dịch trong ngày (intraday)

In [7]:
from vnstock_data import Quote

quote = Quote(symbol='REE')
quote.history(start='2000-07-28', end='2024-08-31', interval='1D')

           time   close    open    high     low   volume
0    2013-01-02   6.058   5.987   6.094   5.987   421680
1    2013-01-03   5.987   6.023   6.094   5.952   624970
2    2013-01-04   6.058   5.987   6.094   5.952   314290
3    2013-01-07   6.094   6.058   6.201   6.058   497270
4    2013-01-08   6.379   6.058   6.379   6.058  1872200
...         ...     ...     ...     ...     ...      ...
2904 2024-08-26  69.048  70.330  70.626  68.456   676600
2905 2024-08-27  67.667  68.653  69.048  67.470   692400
2906 2024-08-28  67.667  67.766  68.062  67.272   530200
2907 2024-08-29  68.062  67.568  68.062  67.470   328800
2908 2024-08-30  67.667  67.766  68.259  67.568   342100

[2909 rows x 6 columns]

In [8]:
quote.intraday()

,time,price,accumulated_val,accumulated_vol,volume,match_type
0,2025-03-21 09:15:03,71.9,970650000,13500,13500,ATO
1,2025-03-21 09:15:12,71.8,977830000,13600,100,Sell
2,2025-03-21 09:16:49,71.8,985010000,13700,100,Buy
3,2025-03-21 09:17:31,71.8,992190000,13800,100,Sell
4,2025-03-21 09:18:19,71.8,999370000,13900,100,Buy
...,...,...,...,...,...,...
721,2025-03-21 14:27:16,71.3,34940020000,487200,200,Buy
722,2025-03-21 14:27:16,71.3,34925760000,487000,100,Buy
723,2025-03-21 14:28:22,71.3,35011320000,488200,1000,Buy
724,2025-03-21 14:29:23,71.4,35018460000,488300,100,Sell
725,2025-03-21 14:45:04,71.5,36362660000,507100,18800,ATC

## 3. Trạng thái niêm yết

In [9]:
from vnstock_data import Listing

Listing().all_symbols()

,code,type,exchange,status,company_name,company_name_eng,short_name,listed_date,delisted_date,company_id,tax_code,isin,short_name_eng,index_code
0,ENF,IFC,UPCOM,delisted,Quỹ Đầu tư Năng động Eastspring Investments Vi...,Eastspring Investments Vietnam Navigator Fund,Quỹ đầu tư ENF,2001-01-01,2001-01-01,3903,NaN,NaN,NaN,NaN
1,VEOF,IFC,HOSE,listed,Công ty Cổ phần Quản lý Quỹ VinaCapital,VinaCaptital Fund Management JSC,Quỹ ETF VinaCapital VN100,2020-07-21,NaN,10762,0305655145,NaN,NaN,NaN
2,VESAF,IFC,HOSE,listed,Công ty Cổ phần Quản lý Quỹ VinaCapital,VinaCaptital Fund Management JSC,Quỹ ETF VinaCapital VN100,2020-07-21,NaN,10762,0305655145,NaN,NaN,NaN
3,VMEEF,IFC,HOSE,listed,Công ty Cổ phần Quản lý Quỹ VinaCapital,VinaCaptital Fund Management JSC,Quỹ ETF VinaCapital VN100,2020-07-21,NaN,10762,0305655145,NaN,NaN,NaN
4,VFMVFA,IFC,HOSE,delisted,Quỹ Đầu tư năng động Việt Nam,Vietnam Active Fund,NaN,2010-08-09,2013-03-11,2862,NaN,VN000VFMVFA5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1944,LEC,STOCK,HOSE,listed,Công ty Cổ phần Bất động sản Điện lực Miền Trung,Central Power Real Estate Joint Stock Company,BĐS Điện lực miền Trung,2017-06-14,NaN,3925,0400592801,VN000000LEC9,Central Power Real Estate,NaN
1945,SBC,STOCK,HOSE,delisted,Công ty Cổ phần Vận tải và Giao nhận Bia Sài Gòn,Saigon Beer Transportation Joint Stock Company,NaN,2010-06-02,2015-02-12,2797,0304082452,NaN,NaN,NaN
1946,BID,STOCK,HOSE,listed,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,Bank for Investment and development of Vietnam,Ngân hàng BIDV,2014-01-24,NaN,446,0100150619,VN000000BID9,BIDV,VN30
1947,GIL,STOCK,HOSE,listed,Công ty Cổ phần Sản Xuất Kinh Doanh Xuất Nhập ...,Binh Thanh Import - Export Production & Trade ...,XNK Bình Thạnh,2002-01-02,NaN,497,0302181666,VN000000GIL1,Binh Thanh Im-export,NaN
1948,CTD,STOCK,HOSE,listed,Công ty Cổ phần Xây dựng Coteccons,Coteccons Construction Joint Stock Company,Xây dựng Coteccons,2010-01-20,NaN,1530,0303443233,VN000000CTD4,COTECCONS,NaN

## 4. Top cổ phiếu

In [10]:
from vnstock_data import TopStock
top = TopStock()

### Top tăng giá

In [11]:
top.gainer()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,HQC,VNINDEX,3.43,2025-03-21 15:59,0.22,6.853583,5.484471e+10,4296475.0,379.529731,4296475.0,0.000000,0.000000,0.0,0.000000e+00,0.0
1,LGL,VNINDEX,3.30,2025-03-21 15:59,0.21,6.796117,8.388990e+08,131470.0,198.904693,131470.0,0.000000,0.000000,0.0,0.000000e+00,0.0
2,VAF,VNINDEX,18.10,2025-03-21 15:59,1.15,6.784661,2.167000e+07,11295.0,10.624170,11295.0,0.000000,0.000000,0.0,0.000000e+00,0.0
3,HAR,VNINDEX,3.68,2025-03-21 15:59,0.22,6.358382,5.768113e+09,226545.0,700.037520,226545.0,0.000000,0.000000,0.0,0.000000e+00,0.0
4,FIR,VNINDEX,8.25,2025-03-21 15:59,0.35,4.430380,4.078709e+09,363330.0,139.515041,363330.0,0.000000,0.000000,0.0,0.000000e+00,0.0
5,DTA,VNINDEX,5.66,2025-03-21 15:59,0.22,4.044118,8.473580e+08,116750.0,127.708779,116750.0,0.000000,0.000000,0.0,0.000000e+00,0.0
6,THG,VNINDEX,60.50,2025-03-21 15:59,2.00,3.418803,1.813660e+09,61010.0,49.500082,61010.0,0.000000,0.000000,0.0,0.000000e+00,0.0
7,APG,VNINDEX,10.55,2025-03-21 15:59,0.30,2.926829,4.637685e+09,470800.0,94.817332,485735.0,0.000000,4.117471,100000.0,1.900000e+08,20000.0
8,VIC,VNINDEX,53.00,2025-03-21 15:59,1.50,2.912621,3.927316e+11,5813650.0,128.771082,7389360.0,1.813418,6.292832,2325000.0,2.425866e+10,465000.0
9,JVC,VNINDEX,5.39,2025-03-21 15:59,0.14,2.666667,4.062581e+09,1193530.0,64.698835,1817420.0,0.000000,0.000000,0.0,0.000000e+00,0.0

### Top giảm giá

In [12]:
top.loser()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,ORS,VNINDEX,11.45,2025-03-21 15:59,-0.85,-6.910569,2.183817e+11,12638620.0,150.652524,12677620.00,0.000000,0.000000,0.0,0.000000e+00,0.0
1,TCD,VNINDEX,2.62,2025-03-21 15:59,-0.18,-6.428571,1.045368e+10,2820890.0,141.005144,2820890.00,0.000000,0.000000,0.0,0.000000e+00,0.0
2,BCG,VNINDEX,3.74,2025-03-21 15:59,-0.18,-4.591837,9.236037e+10,23129320.0,105.916646,23220500.55,0.000220,0.000044,51.0,3.723000e+04,10.2
3,TMT,VNINDEX,14.00,2025-03-21 15:59,-0.50,-3.448276,1.685450e+08,38380.0,30.745180,38380.00,0.000000,0.000000,0.0,0.000000e+00,0.0
4,VRC,VNINDEX,14.10,2025-03-21 15:59,-0.50,-3.424658,7.080900e+08,62250.0,79.839357,62250.00,0.000000,0.000000,0.0,0.000000e+00,0.0
5,POW,VNINDEX,12.45,2025-03-21 15:59,-0.40,-3.112840,1.804970e+11,7909245.0,181.323249,7929245.00,0.000000,0.000000,0.0,0.000000e+00,0.0
6,TPB,VNINDEX,14.75,2025-03-21 15:59,-0.45,-2.960526,5.688112e+11,21077435.0,181.548182,21378230.85,1.774239,2.467838,2637901.0,8.368768e+09,527580.2
7,VID,VNINDEX,5.21,2025-03-21 15:59,-0.14,-2.616822,4.961200e+07,11780.0,79.796265,11780.00,0.000000,0.000000,0.0,0.000000e+00,0.0
8,YBM,VNINDEX,15.10,2025-03-21 15:59,-0.40,-2.580645,7.112900e+08,68775.0,69.501999,75005.00,0.000000,0.000000,0.0,0.000000e+00,0.0
9,TYA,VNINDEX,17.15,2025-03-21 15:59,-0.45,-2.556818,1.545800e+08,28400.0,31.690141,28400.00,0.000000,0.000000,0.0,0.000000e+00,0.0

### Top theo GTGD lớn nhất

In [13]:
top.value()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,SHB,VNINDEX,11.75,2025-03-21 15:59,0.00,0.000000,8.834236e+11,40255260.0,185.333792,49304262.55,25.504900,21.902692,53994803.0,1.226396e+11,10798960.6
1,FPT,VNINDEX,128.00,2025-03-21 15:59,3.00,2.400000,8.202042e+11,6297220.0,102.025973,6763434.75,0.000000,7.916688,2677200.0,6.895731e+10,535440.0
2,VHM,VNINDEX,48.25,2025-03-21 15:59,0.90,1.900739,6.590011e+11,11663385.0,117.424744,13762536.00,0.000000,0.000000,0.0,0.000000e+00,0.0
3,VND,VNINDEX,15.35,2025-03-21 15:59,0.20,1.320132,6.331446e+11,23973240.0,171.344382,24002740.00,0.000000,0.266636,320000.0,9.600000e+08,64000.0
4,TPB,VNINDEX,14.75,2025-03-21 15:59,-0.45,-2.960526,5.688112e+11,21077435.0,181.548182,21378230.85,1.774239,2.467838,2637901.0,8.368768e+09,527580.2
5,SSI,VNINDEX,26.60,2025-03-21 15:59,0.05,0.188324,5.655269e+11,28713380.0,73.852329,30088910.05,0.978769,6.952463,10459601.0,5.743446e+10,2091920.2
6,HPG,VNINDEX,27.15,2025-03-21 15:59,0.00,0.000000,5.135383e+11,29746145.0,63.578659,30426510.60,10.869508,2.732756,4157412.0,2.270286e+10,831482.4
7,VCI,VNINDEX,39.10,2025-03-21 15:59,-0.10,-0.255102,5.036825e+11,9783660.0,131.006188,9790660.00,0.000000,0.000000,0.0,0.000000e+00,0.0
8,VIC,VNINDEX,53.00,2025-03-21 15:59,1.50,2.912621,3.927316e+11,5813650.0,128.771082,7389360.00,1.813418,6.292832,2325000.0,2.425866e+10,465000.0
9,MBB,VNINDEX,24.30,2025-03-21 15:59,0.05,0.206186,3.789678e+11,22330135.0,69.715208,24755989.30,10.502545,7.189358,8898984.0,4.375129e+10,1779796.8

### Top theo KLGD

In [14]:
top.volume()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,HAR,VNINDEX,3.68,2025-03-21 15:59,0.22,6.358382,5.768113e+09,226545.0,700.037520,226545.0,0.000000,0.000000,0.0,0.000000e+00,0.0
1,CKG,VNINDEX,20.00,2025-03-21 15:59,0.30,1.522843,5.370485e+09,58490.0,457.856044,70720.0,0.000000,0.000000,0.0,0.000000e+00,0.0
2,HQC,VNINDEX,3.43,2025-03-21 15:59,0.22,6.853583,5.484471e+10,4296475.0,379.529731,4296475.0,0.000000,0.000000,0.0,0.000000e+00,0.0
3,DLG,VNINDEX,2.10,2025-03-21 15:59,-0.02,-0.943396,1.097289e+10,1689325.0,297.686946,2428825.0,0.000000,119.728675,14540000.0,5.816000e+09,2908000.0
4,NAB,VNINDEX,17.30,2025-03-21 15:59,-0.25,-1.424501,1.394756e+11,3007450.0,268.164059,10494484.8,63.911665,73.795714,38722400.0,1.395588e+11,7744480.0
5,C32,VNINDEX,19.70,2025-03-21 15:59,0.00,0.000000,1.899090e+09,40335.0,238.998388,48105.0,0.000000,0.000000,0.0,0.000000e+00,0.0
6,BCE,VNINDEX,10.30,2025-03-21 15:59,0.00,0.000000,4.606969e+09,190450.0,235.652402,190450.0,0.000000,0.000000,0.0,0.000000e+00,0.0
7,VPI,VNINDEX,56.80,2025-03-21 15:59,-0.40,-0.699301,2.441077e+11,1849340.0,230.703927,1871340.0,0.000000,0.000000,0.0,0.000000e+00,0.0
8,LGL,VNINDEX,3.30,2025-03-21 15:59,0.21,6.796117,8.388990e+08,131470.0,198.904693,131470.0,0.000000,0.000000,0.0,0.000000e+00,0.0
9,SJS,VNINDEX,101.00,2025-03-21 15:59,1.00,1.000000,4.301100e+09,22335.0,190.284307,614835.0,483.056430,154.708174,4756000.0,9.818294e+10,951200.0

### Top GD thoả thuận

In [15]:
top.deal()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,OCB,VNINDEX,11.00,2025-03-21 15:59,-0.15,-1.345291,3.472276e+10,2791010.0,111.869897,3953610.00,587.184877,117.624146,23252000.0,5.347479e+10,4650400.0
1,SJS,VNINDEX,101.00,2025-03-21 15:59,1.00,1.000000,4.301100e+09,22335.0,190.284307,614835.00,483.056430,154.708174,4756000.0,9.818294e+10,951200.0
2,DBD,VNINDEX,58.00,2025-03-21 15:59,-0.20,-0.343643,6.043190e+09,199585.0,52.208332,388195.00,177.745721,79.959814,1552000.0,1.810900e+10,310400.0
3,CTF,VNINDEX,20.45,2025-03-21 15:59,-0.05,-0.243902,6.440910e+09,213160.0,149.465190,522985.10,152.968029,81.256617,2124800.0,8.637184e+09,424960.0
4,SSB,VNINDEX,19.85,2025-03-21 15:59,0.00,0.000000,3.917985e+10,1833875.0,108.246200,6062609.15,112.080456,116.929854,35445000.0,1.403062e+11,7089000.0
5,HVH,VNINDEX,9.55,2025-03-21 15:59,0.07,0.738397,9.353110e+08,205165.0,47.766432,246165.00,81.246319,16.249264,200000.0,3.560000e+08,40000.0
6,ACB,VNINDEX,26.10,2025-03-21 15:59,-0.15,-0.571429,1.081152e+11,7325315.0,56.405765,9871088.30,78.230391,20.686860,10210091.0,5.609151e+10,2042018.2
7,NAB,VNINDEX,17.30,2025-03-21 15:59,-0.25,-1.424501,1.394756e+11,3007450.0,268.164059,10494484.80,63.911665,73.795714,38722400.0,1.395588e+11,7744480.0
8,SIP,VNINDEX,90.10,2025-03-21 15:59,0.10,0.111111,1.202048e+11,779900.0,170.932171,805900.00,37.225462,7.445092,300000.0,5.406000e+09,60000.0
9,PET,VNINDEX,23.10,2025-03-21 15:59,0.10,0.434783,6.109920e+09,539190.0,48.925240,585190.00,35.885781,14.354312,420000.0,1.969800e+09,84000.0

### Top NĐTNN mua ròng

In [16]:
top.foreign_buy(date='2024-08-16')

  symbol        date     net_value
0    MWG  2024-08-16  1.015998e+11
1    CTG  2024-08-16  6.709855e+10
2    DIG  2024-08-16  6.705117e+10
3    MSN  2024-08-16  6.318864e+10
4    VCI  2024-08-16  5.041683e+10
5    VND  2024-08-16  3.089996e+10
6    NVL  2024-08-16  3.054193e+10
7    DPM  2024-08-16  2.839805e+10
8    DGC  2024-08-16  2.769208e+10
9    FPT  2024-08-16  2.629880e+10

### Top NĐTNN bán ròng

In [17]:
top.foreign_sell(date='2024-08-16')

     symbol        date     net_value
0       VHM  2024-08-16 -3.136147e+11
1       HPG  2024-08-16 -1.804457e+11
2       TCB  2024-08-16 -1.083005e+11
3       HSG  2024-08-16 -5.660693e+10
4       VPB  2024-08-16 -4.944804e+10
5  FUEVFVND  2024-08-16 -3.769779e+10
6       FRT  2024-08-16 -3.130877e+10
7       HDB  2024-08-16 -2.534124e+10
8       QNS  2024-08-16 -1.809028e+10
9       NLG  2024-08-16 -1.657578e+10

## 5. Phân tích thị trường

In [18]:
from vnstock_data import Market

market = Market(index='VNINDEX')

In [19]:
market.pe()

                   pe
reportDate
2020-03-23  10.443731
2020-03-24  10.329050
2020-03-25  10.812168
2020-03-26  10.873666
2020-03-27  10.903200
...               ...
2025-03-17  13.263778
2025-03-18  13.210796
2025-03-19  13.147344
2025-03-20  13.141230
2025-03-21  13.120329

[1245 rows x 1 columns]

In [20]:
market.pb()

                  pb
reportDate
2020-03-23  1.831608
2020-03-24  1.811600
2020-03-25  1.896378
2020-03-26  1.907164
2020-03-27  1.912355
...              ...
2025-03-17  1.715332
2025-03-18  1.708441
2025-03-19  1.700305
2025-03-20  1.699462
2025-03-21  1.696856

[1245 rows x 1 columns]

In [21]:
market.evaluation()

                   pe        pb
reportDate
2020-03-23  10.443731  1.831608
2020-03-24  10.329050  1.811600
2020-03-25  10.812168  1.896378
2020-03-26  10.873666  1.907164
2020-03-27  10.903200  1.912355
...               ...       ...
2025-03-17  13.263778  1.715332
2025-03-18  13.210796  1.708441
2025-03-19  13.147344  1.700305
2025-03-20  13.141230  1.699462
2025-03-21  13.120329  1.696856

[1245 rows x 2 columns]

## 6. Giá hàng hoá

In [22]:
from vnstock_data import CommodityPrice

# Khởi tạo đối tượng CommodityPrice với ngày mặc định
commodity = CommodityPrice(start="2022-01-03", end="2024-12-31")

# Lấy dữ liệu giá vàng
gold_vn = commodity.gold_vn()  # Giá vàng Việt Nam (mua vào)
print("Gold VN:\n", gold_vn)

gold_global = commodity.gold_global()  # Giá vàng thế giới
print("Gold Global:\n", gold_global)

# Lấy dữ liệu giá xăng
gas_vn = commodity.gas_vn()  # Giá xăng RON92
print("Gas VN:\n", gas_vn)

oil_crude = commodity.oil_crude()  # Giá dầu thô
print("Oil Crude:\n", oil_crude)

# Lấy dữ liệu khí thiên nhiên
gas_natural = commodity.gas_natural()  # Giá khí thiên nhiên
print("Gas Natural:\n", gas_natural)

# Lấy dữ liệu giá than
coke = commodity.coke()  # Giá than cốc
print("Coke:\n", coke)

# Lấy dữ liệu giá thép
steel_d10 = commodity.steel_d10()  # Giá thép D10
print("Steel D10:\n", steel_d10)

steel_hrc = commodity.steel_hrc()  # Giá thép HRC
print("Steel HRC:\n", steel_hrc)

# Lấy dữ liệu giá quặng sắt
iron_ore = commodity.iron_ore()  # Giá quặng sắt
print("Iron Ore:\n", iron_ore)

# Lấy dữ liệu giá phân bón
fertilizer_ure = commodity.fertilizer_ure()  # Giá phân ure
print("Fertilizer URE:\n", fertilizer_ure)

# Lấy dữ liệu giá nông sản
soybean = commodity.soybean()  # Giá đậu tương
print("Soybean:\n", soybean)

corn = commodity.corn()  # Giá ngô (bắp)
print("Corn:\n", corn)

sugar = commodity.sugar()  # Giá đường
print("Sugar:\n", sugar)

# Lấy dữ liệu giá heo hơi
pork_north_vn = commodity.pork_north_vn()  # Giá heo hơi miền Bắc Việt Nam
print("Pork North VN:\n", pork_north_vn)

pork_china = commodity.pork_china()  # Giá heo hơi Trung Quốc
print("Pork China:\n", pork_china)

Gold VN:
                 buy     sell
time
2022-01-03  60900.0  61600.0
2022-01-04  61000.0  61700.0
2022-01-05  60750.0  61450.0
2022-01-06  60900.0  61600.0
2022-01-09  60900.0  61650.0
...             ...      ...
2024-12-25  82300.0  84300.0
2024-12-26  82500.0  84500.0
2024-12-27  82700.0  84700.0
2024-12-28  82700.0  84700.0
2024-12-30  82500.0  84500.0

[791 rows x 2 columns]
Gold Global:
               open    high     low   close    volume
time
2022-01-03  1830.1  1833.0  1798.2  1800.1  168305.0
2022-01-04  1801.1  1817.2  1798.1  1814.6  167708.0
2022-01-05  1815.2  1830.7  1808.2  1825.1  173344.0
2022-01-06  1810.6  1811.6  1785.4  1789.2  238644.0
2022-01-07  1791.0  1798.4  1781.3  1797.4  238931.0
...            ...     ...     ...     ...       ...
2024-12-23  2639.1  2646.8  2623.2  2628.2  100814.0
2024-12-24  2629.4  2635.8  2624.2  2635.5   52221.0
2024-12-26  2638.0  2655.7  2634.1  2653.9   77712.0
2024-12-27  2653.7  2654.6  2625.2  2631.9   92262.0
2024-12-30  2636.1  2640.7  2608.4  2618.1  110915.0

[822 rows x 5 columns]
Gas VN:
             ron95  ron92  oil_do
time
2022-01-15  23.87  23.15   18.23
2022-01-16  23.87  23.15   18.23
2022-01-17  23.87  23.15   18.23
2022-01-18  23.87  23.15   18.23
2022-01-19  23.87  23.15   18.23
...           ...    ...     ...
2024-12-26  20.54  19.81   18.63
2024-12-27  20.54  19.81   18.63
2024-12-28  20.54  19.81   18.63
2024-12-29  20.54  19.81   18.63
2024-12-30  20.54  19.81   18.63

[1000 rows x 3 columns]
Oil Crude:
              open   high    low  close    volume
time
2022-01-03  75.69  76.46  74.27  76.08  317628.0
2022-01-04  76.02  77.64  75.70  76.99  372848.0
2022-01-05  77.18  78.58  76.51  77.85  397898.0
2022-01-06  77.24  80.24  76.73  79.46  476665.0
2022-01-07  79.62  80.47  78.52  78.90  414434.0
...           ...    ...    ...    ...       ...
2024-12-23  69.40  69.94  68.59  69.24  174319.0
2024-12-24  69.56  70.43  69.36  70.10  108539.0
2024-12-26  70.20  70.75  69.33  69.62  128387.0
2024-12-27  69.68  70.75  69.44  70.60  158886.0
2024-12-30  70.42  71.56  70.12  70.99  183540.0

[823 rows x 5 columns]
Gas Natural:
              open   high    low  close   volume
time
2022-01-03  3.725  3.855  3.635  3.815   5288.0
2022-01-04  3.830  3.945  3.705  3.715   5781.0
2022-01-05  3.750  3.895  3.720  3.880   4507.0
2022-01-06  3.840  3.930  3.805  3.810   5656.0
2022-01-07  3.865  3.980  3.785  3.915   5335.0
...           ...    ...    ...    ...      ...
2024-12-23  3.500  3.545  3.285  3.345   4071.0
2024-12-24  3.385  3.510  3.360  3.505   4559.0
2024-12-26  3.520  3.525  3.250  3.320   5439.0
2024-12-27  3.325  3.450  3.290  3.385   6227.0
2024-12-30  3.650  4.205  3.645  3.935  18093.0

[822 rows x 5 columns]
Coke:
               open    high     low   close  volume
time
2022-01-03  151.45  151.45  151.45  151.45     2.0
2022-01-04  166.50  168.00  161.00  161.10   383.0
2022-01-05  165.00  165.00  161.00  161.65   171.0
2022-01-06  175.00  181.00  175.00  180.00   100.0
2022-01-07  195.00  196.75  177.00  177.00   536.0
...            ...     ...     ...     ...     ...
2024-12-23  125.50  125.50  125.50  125.50    29.0
2024-12-24  125.00  125.00  125.00  125.00    10.0
2024-12-26  126.50  126.50  126.50  126.50     0.0
2024-12-27  126.40  126.40  126.30  126.30    55.0
2024-12-30  125.75  125.90  125.75  125.90    75.0

[772 rows x 5 columns]
Steel D10:
                 close
time
2022-01-14  16.410000
2022-01-15  16.410000
2022-01-16  16.683333
2022-01-17  16.683333
2022-01-18  16.683333
...               ...
2024-12-26  13.940000
2024-12-27  13.940000
2024-12-28  13.940000
2024-12-29  13.940000
2024-12-30  13.940000

[1000 rows x 1 columns]
Steel HRC:
               open    high     low   close  volume
time
2022-01-03  1435.0  1439.0  1435.0  1438.0    32.0
2022-01-04  1435.0  1440.0  1435.0  1435.0   642.0
2022-01-05  1435.0  1435.0  1425.0  1426.0   312.0
2022-01-06  1420.0  1425.0  1410.0  1420.0   263.0
2022-01-07  1419.0  1420.0  1405.0  1415.0   176.0
...            ...     ...     ...     ...     ...
2024-12-23   685.0   685.0   677.0   683.0    92.0
2024-12-24   729.0   729.0   723.0   725.0   144.0
2024-12-26   720.0   740.0   720.0   720.0    60.0
2024-12-27   730.0   730.0   730.0   730.0   100.0
2024-12-30   725.0   732.0   718.0   725.0   115.0

[752 rows x 5 columns]
Iron Ore:
               open    high     low   close  volume
time
2022-01-03  120.40  120.40  120.40  120.40     0.0
2022-01-04  120.91  120.91  120.91  120.91     0.0
2022-01-05  124.14  124.14  124.14  124.14   200.0
2022-01-06  125.94  125.94  125.94  125.94     0.0
2022-01-07  126.21  126.21  126.21  126.21     0.0
...            ...     ...     ...     ...     ...
2024-12-23  103.84  103.84  103.84  103.84     0.0
2024-12-24  104.08  104.08  104.08  104.08     0.0
2024-12-26  104.08  104.08  104.08  104.08     0.0
2024-12-27  103.90  103.90  103.90  103.90     0.0
2024-12-30  100.73  100.73  100.73  100.73     0.0

[757 rows x 5 columns]
Fertilizer URE:
              open   high    low  close  volume
time
2022-01-03  842.5  842.5  842.5  842.5     0.0
2022-01-04  842.5  842.5  842.5  842.5     0.0
2022-01-05  830.0  830.0  830.0  830.0     0.0
2022-01-06  835.0  835.0  835.0  835.0     0.0
2022-01-07  835.0  835.0  835.0  835.0     0.0
...           ...    ...    ...    ...     ...
2024-12-23  366.0  366.0  366.0  366.0     0.0
2024-12-24  366.0  366.0  366.0  366.0     0.0
2024-12-26  366.0  366.0  366.0  366.0     0.0
2024-12-27  369.0  369.0  369.0  369.0     0.0
2024-12-30  369.0  369.0  369.0  369.0     0.0

[729 rows x 5 columns]
Soybean:
                open     high      low    close    volume
time
2022-01-03  1349.00  1368.50  1342.00  1355.50   90234.0
2022-01-04  1356.00  1392.25  1355.50  1389.75  122661.0
2022-01-05  1389.00  1399.00  1381.50  1394.75   96172.0
2022-01-06  1390.50  1393.75  1370.00  1387.25   99489.0
2022-01-07  1388.00  1415.00  1376.00  1410.25  129914.0
...             ...      ...      ...      ...       ...
2024-12-23   979.50   984.00   972.75   975.50  105210.0
2024-12-24   974.50   981.75   971.75   981.25   64012.0
2024-12-26   985.00   998.00   981.00   997.25  135969.0
2024-12-27   995.75   998.25   988.50   989.75  104442.0
2024-12-30   994.25  1004.50   986.75   991.75  140332.0

[752 rows x 5 columns]
Corn:
               open    high     low   close    volume
time
2022-01-03  599.00  603.50  584.75  589.25  146023.0
2022-01-04  591.75  611.25  591.50  609.50  210268.0
2022-01-05  608.50  609.75  601.25  602.25  148499.0
2022-01-06  601.25  605.75  596.00  603.75  151442.0
2022-01-07  605.25  608.25  599.00  606.75  140371.0
...            ...     ...     ...     ...       ...
2024-12-23  446.00  448.25  445.25  447.75  132878.0
2024-12-24  447.25  448.75  446.75  448.50   88153.0
2024-12-26  448.50  454.25  448.50  453.75  176165.0
2024-12-27  453.25  455.00  452.25  454.00  162024.0
2024-12-30  453.75  458.50  449.75  452.25  217069.0

[811 rows x 5 columns]
Sugar:
              open   high    low  close   volume
time
2022-01-03  18.94  19.01  18.68  18.74  20398.0
2022-01-04  18.75  18.85  18.62  18.75  40168.0
2022-01-05  18.80  18.80  18.32  18.34  59414.0
2022-01-06  18.31  18.39  18.15  18.19  46247.0
2022-01-07  18.26  18.44  17.99  18.05  46856.0
...           ...    ...    ...    ...      ...
2024-12-23  19.60  19.79  19.42  19.54  39966.0
2024-12-24  19.60  19.82  19.50  19.54  22290.0
2024-12-26  19.51  19.54  19.17  19.26  26005.0
2024-12-27  19.24  19.45  19.18  19.37  34311.0
2024-12-30  19.37  19.66  19.05  19.13  43046.0

[753 rows x 5 columns]
Pork North VN:
               close
time
2022-01-10  58000.0
2022-01-17  56562.5
2022-01-24  54312.5
2022-02-03  53987.5
2022-02-10  54037.5
...             ...
2024-12-24  68600.0
2024-12-25  68300.0
2024-12-26  68100.0
2024-12-29  67700.0
2024-12-30  67900.0

[409 rows x 1 columns]
Pork China:
             close
time
2022-01-08  14.52
2022-01-15  13.67
2022-01-22  13.33
2022-02-01  13.21
2022-02-08  12.88
...           ...
2024-11-26  17.10
2024-12-03  16.92
2024-12-10  16.65
2024-12-17  16.56
2024-12-24  16.44

[157 rows x 1 columns]